resilience4j:
  circuitbreaker:
    config:
      shared:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
    instances:
      example:
        base-config: shared

